[package]
name = "rsexp"
version = "0.1.0"
edition = "2018"

[dependencies]
nom = "7.0"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
clap = "3.0.0-beta.4"
tracing = "0.1"
tracing-subscriber = "0.2"
